### ISSUE TITLE
Q: How to deal with Terraform drift for existing routes? 

### ISSUE THREAD

**Issue by oponomarov-tu** [1debit/alternat#49]
In our environment we create routes to `0.0.0.0/0` to be managed by NAT gateways by default, like this:

```hcl
resource "aws_route" "private_route_per_az" {
    destination_cidr_block = "0.0.0.0/0"
    id                     = "r-rtb-<id>"
    nat_gateway_id         = "nat-<id>"
    origin                 = "CreateRoute"
    route_table_id         = "rtb-<id>"
    state                  = "active"
}
```

Once AlterNAT is deployed and updates the route, — we see a drift the next time Terraform plan is ran:

```hcl
  # module.infra.aws_route.private_route_per_az["nat-<id>"] will be updated in-place
  ~ resource "aws_route" "private_route_per_az" {
        id                     = "r-rtb-<id>"
      + nat_gateway_id         = "nat-<id>"
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

So far I've managed to silence the noise by applying `ignore_changes` on the drifted resource, e.g.:

```hcl
  lifecycle {
    ignore_changes = all
  }
```

**My question**: is there a better way around this? Thanks!

**Comment by bwhaley** [comment]
In case some future person who is using [the open source `terraform-aws-vpc` module](https://github.com/terraform-aws-modules/terraform-aws-vpc) runs in to this and wants to set `create_nat_gateway=false` in alternat:

I noticed that the terraform-aws-vpc module sets the NAT Gateway destination cidr block [using a variable](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/2a0319ec3244169997c6dac0d7850897ba9b9162/main.tf#L1055) that defaults to `0.0.0.0/0`. As a hacky workaround, you could set `nat_gateway_destination_cidr_block` to some value that the network is unlikely to use, like `192.0.2.0/24` (this is an example CIDR range as per [RFC5735](https://www.rfc-editor.org/rfc/rfc5735). You'd then have a route to a network that doesn't really exist, and alterNAT can still manage the route to 0.0.0.0/0.
