### ISSUE TITLE
Sync connection table using conntrackd or similar

### ISSUE THREAD

**Issue by lukasmrtvy** [1debit/alternat#67]
Hey, 
Just a quick idea, not sure if it's even doable, but what about using conntrackd for syncing conntack table to another node which can be a passive instance?  

According to this https://docs.aws.amazon.com/whitepapers/latest/real-time-communication-on-aws/floating-ip-pattern-for-ha-between-activestandby-stateful-servers.html#applicability-in-rtc-solutions Keepalived should work.

Or it could be even a newly created instance where can be a conntrack table imported when a reboot would be required. Optional locking can be done via AWSSM.

Thanks

**Comment by bwhaley** [comment]
This is a good idea, and it has come up before. It'd be a nice solution to the connection table problem. I'm probably not going to have time to implement this any time soon, but if anyone wants to have a go, I'd definitely be able to review PRs!

**Comment by bwhaley** [comment]
Closing this since it hasn't been active in a while. Do feel free to submit a PR if you'd like to see this enhancement!
