### ISSUE TITLE
ARM Lambda Option

### ISSUE THREAD

**Issue by therealvio** [1debit/alternat#70]
Hi team,

First off, thanks for this excellent project!

I have been working on setting up alterNAT to replace our NAT gateways for our more _active_ AWS accounts. I noticed there isn't an option for running the Lambdas in ARM architecture. It would be a neat little cost optimization given how often the connectivity Lambda runs alone.

Admittedly, I am not familiar with how Python works with ARM CPU architecture - so I can imagine this making it tricky.

Thanks in advance!

**Comment by bwhaley** [comment]
Seems reasonable to me. Would you be willing to give #71 a try and let me know if that works for you?

**Comment by therealvio** [comment]
Yeah, I will try to make some time tomorrow (Australian Eastern) to give it a whirl 👍

If it works out, my plan is to share details on how it runs too.
